// Generated by scripts/build-werewolf-edge.mjs; edit api/src/werewolf instead.
'use strict';
// The service key exists only inside the Edge Function. The browser cannot read
// this table or execute either RPC. UUID versions prevent ABA after code reuse.
class SupabaseRoomStore {
  constructor(url, key, fetcher = fetch) {
    if (!url || !key) throw new Error('Werewolf storage is not configured.');
    this.url = `${url.replace(/\/$/, '')}/rest/v1/rpc/`;
    this.key = key; this.fetcher = fetcher;
  }
  async rpc(name, body) {
    const response = await this.fetcher(this.url + name, {
      method: 'POST', headers: { apikey: this.key, Authorization: `Bearer ${this.key}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(body), signal: AbortSignal.timeout(10000),
    });
    if (!response.ok) throw new Error(`Room storage unavailable (${response.status}).`);
    return response.json();
  }
  async read(key) { return this.rpc('werewolf_read', { p_key: key }); }
  async write(key, value, version) {
    return this.rpc('werewolf_cas', { p_key: key, p_value: value, p_version: version || null });
  }
  async transact(key, callback) {
    for (let attempt = 0; attempt < 12; attempt++) {
      const entry = await this.read(key);
      const { value, result, changed = true } = await callback(entry?.value ?? null);
      if (!changed || await this.write(key, value, entry?.version)) return result;
      await new Promise(resolve => setTimeout(resolve, 15 + Math.random() * Math.min(150, attempt * 25)));
    }
    const error = new Error('The room is busy. Please retry.');
    error.code = 'room-busy'; error.status = 409; error.clientSafe = true; throw error;
  }
}
export { SupabaseRoomStore };
