'use client';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown, ArrowClockwise, Trash } from '@phosphor-icons/react';
import { selectionLimits } from './cellLayout';
import { KIND_NAMES, type ComponentKind, type KitchenDesign, type KitchenComponent } from './kitchen';
import { defaultWalls, fitOpenings, editOpening as resolveOpening, addOpening, WALL_SIDES, wallLength, type WallSide, type RoomOpening } from './room';
import { ColorPicker } from './FinishControls';
import styles from './studio.module.css';
export function NumberEdit({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void}){
  return <label className={styles.directNumber}>{label}<span><input key={value} type="number" aria-label={label} defaultValue={value} min={min} max={max} step={.5} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onBlur={e=>{if(Number.isFinite(e.target.valueAsNumber)){const n=Math.max(min,Math.min(max,Math.round(e.target.valueAsNumber*2)/2));if(n!==value)onChange(n);}e.target.value=String(value);}}/>″</span></label>;
}
function SizeControl({label,value,mixed,limits,onChange}:{label:string;value:number;mixed:boolean;limits:[number,number]|null;onChange:(n:number)=>void}){
  const [min,max]=limits??[value,value];
  return <div className={styles.sizeControl}><label>{label}<span><input key={`${value}:${mixed}:${min}:${max}`} aria-label={`${label} in inches`} type="number" inputMode="decimal" step={.5} min={min} max={max} placeholder="Mixed" defaultValue={mixed?'':value} disabled={!limits} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onBlur={e=>{if(Number.isFinite(e.target.valueAsNumber)){const n=Math.max(min,Math.min(max,Math.round(e.target.valueAsNumber*2)/2));onChange(n);e.target.value=String(n);}else e.target.value=mixed?'':String(value);}}/>″</span></label><input aria-label={`${label} slider`} type="range" min={min} max={max} step={.5} value={Math.max(min,Math.min(max,value))} disabled={!limits||min===max} onChange={e=>onChange(Number(e.target.value))}/><small>{limits?`${min}–${max}″ available`:'No common size fits this selection'}</small></div>;
}
interface Props { design:KitchenDesign; selected:string|null; selectedIds:string[]; multiSelect:boolean; onMultiSelect:(value:boolean)=>void; onSelect:(id:string|null)=>void; onChange:(d:KitchenDesign)=>void; onEdit:(p:Partial<KitchenComponent>)=>unknown; onReplace:(kind:ComponentKind)=>void; onShift:(x:number,y:number)=>void; onHide:(id:string)=>void; onBoundary:(side:WallSide,delta:number)=>void; notice:string; }
export default function DirectEditor({design,selected,selectedIds,multiSelect,onMultiSelect,onSelect,onChange,onEdit,onReplace,onShift,onHide,onBoundary,notice}:Props){
  const [step,setStep]=useState(1),[openingNotice,setOpeningNotice]=useState('');
  const c=design.components.find(c=>c.id===selected),o=fitOpenings(design).find(o=>o.id===selected);
  const parts=design.components.filter(c=>selectedIds.includes(c.id));
  const limits=useMemo(()=>({width:selectionLimits(design,selectedIds,'width'),depth:selectionLimits(design,selectedIds,'depth')}),[design,selectedIds]);
  const side=selected?.startsWith('wall:')?selected.slice(5) as WallSide:null;
  const walls=design.roomWalls??defaultWalls();
  const editOpening=(patch:Partial<RoomOpening>)=>{if(!o)return;const next=resolveOpening(design,{...o,...patch});if(next){onChange(next);setOpeningNotice('');}else setOpeningNotice('Leave space between window and door frames.');};
  return <div className={styles.directBody}>
    <div className={styles.pieceHeading}><h3>{multiSelect?`${parts.length} selected`:c?.name??(o?`${o.kind==='window'?'Window':'Door'}`:side?`${side[0].toUpperCase()+side.slice(1)} wall`:'Choose a piece')}</h3>{!selected&&<p>Click a component in the room to edit it.</p>}</div>
    <label className={styles.multiSelect}><input type="checkbox" checked={multiSelect} onChange={e=>onMultiSelect(e.target.checked)}/>Select multiple</label>
    {multiSelect&&<><p className={styles.directHint}>Tap pieces to select or deselect. Sizes apply to all selected pieces.</p><details className={styles.simpleDetails}><summary>Choose pieces from a list</summary><div className={styles.multiList}>{design.components.map((part,i)=><label key={part.id}><input type="checkbox" checked={selectedIds.includes(part.id)} onChange={()=>onSelect(part.id)}/>{part.name} · {i+1}</label>)}</div></details></>}
    {!selected&&!multiSelect&&<><details className={styles.simpleDetails}><summary>Choose from a list</summary><label className={styles.selectLabel}>Select an element to edit<select value="" onChange={e=>onSelect(e.target.value||null)}><option value="">Select in the scene</option>{design.components.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></details></>}
    {c&&!multiSelect&&<>
      <label className={styles.selectLabel}>Component<select aria-label="Component type" value={c.kind} onChange={e=>onReplace(e.target.value as ComponentKind)}>{Object.entries(KIND_NAMES).map(([kind,name])=><option key={kind} value={kind}>{name}</option>)}</select></label>
      <div className={styles.directActions}><button onClick={()=>onEdit({rotation:(c.rotation+90)%360})}><ArrowClockwise size={16}/>Rotate 90°</button><button className={styles.removeComponent} onClick={()=>{onChange({...design,components:design.components.filter(p=>p.id!==c.id)});onSelect(null);}}><Trash size={16}/>Delete</button></div>
      <div className={styles.cellArrows} role="group" aria-label="Move or swap one cell"><button aria-label="Shift up" onClick={()=>onShift(0,1)}><ArrowUp size={20}/></button><button aria-label="Shift left" onClick={()=>onShift(-1,0)}><ArrowLeft size={20}/></button><span aria-hidden="true">Move</span><button aria-label="Shift right" onClick={()=>onShift(1,0)}><ArrowRight size={20}/></button><button aria-label="Shift down" onClick={()=>onShift(0,-1)}><ArrowDown size={20}/></button></div>
    </>}
    {!!parts.length&&<>
      <SizeControl label="Width" value={parts[0].width} mixed={parts.some(p=>p.width!==parts[0].width)} limits={limits.width} onChange={width=>onEdit({width})}/>
      <SizeControl label="Length" value={parts[0].depth} mixed={parts.some(p=>p.depth!==parts[0].depth)} limits={limits.depth} onChange={depth=>onEdit({depth})}/>
    </>}
    {o&&<div className={styles.shiftControls}><span>Move</span>{[{name:'left',x:-1,y:0,Icon:ArrowLeft},{name:'right',x:1,y:0,Icon:ArrowRight},{name:'up',x:0,y:1,Icon:ArrowUp},{name:'down',x:0,y:-1,Icon:ArrowDown}].map(({name,x,y,Icon})=><button key={name} aria-label={`Shift ${name}`} onClick={()=>editOpening(x?{offset:o.offset+x*step}:{bottom:o.bottom+y*step})}><Icon size={18}/></button>)}<select aria-label="Shift distance" value={step} onChange={e=>setStep(Number(e.target.value))}>{[1,3,6,12].map(n=><option key={n} value={n}>{n}″</option>)}</select></div>}
    {o&&<><label className={styles.selectLabel}>Wall<select value={o.wall} onChange={e=>editOpening({wall:e.target.value as WallSide})}>{WALL_SIDES.map(s=><option key={s}>{s}</option>)}</select></label><div className={styles.directNumbers}><NumberEdit label="Opening width" value={o.width} min={12} max={144} onChange={width=>editOpening({width})}/><NumberEdit label="Opening height" value={o.height} min={12} max={140} onChange={height=>editOpening({height})}/><NumberEdit label="Sill height" value={o.bottom} min={0} max={144} onChange={bottom=>editOpening({bottom})}/><NumberEdit label="Along wall" value={o.offset} min={-wallLength(design,o.wall)/2} max={wallLength(design,o.wall)/2} onChange={offset=>editOpening({offset})}/></div><div className={styles.directActions}><button onClick={()=>onHide(o.id)}>Hide</button><button onClick={()=>{onChange({...design,openings:fitOpenings(design).filter(p=>p.id!==o.id)});onSelect(null);}}>Remove</button></div></>}
    {side&&<><label className={styles.flowToggle}><input type="checkbox" checked={walls[side].enabled} onChange={e=>onChange({...design,roomWalls:{...walls,[side]:{...walls[side],enabled:e.target.checked}}})}/>Include {side} wall</label><NumberEdit label="Wall height" value={walls[side].height} min={96} max={144} onChange={height=>{const d={...design,roomWalls:{...walls,[side]:{...walls[side],height}}};onChange({...d,openings:fitOpenings(d)});}}/>{!design.gridColumns&&<div className={styles.directActions}><button onClick={()=>onBoundary(side,-12)}>Move inward 12″</button><button onClick={()=>onBoundary(side,12)}>Move outward 12″</button></div>}<p className={styles.directHint}>Windows stay attached to their wall.</p><ColorPicker label="Wall colour" value={design.wallColor} onChange={wallColor=>onChange({...design,wallColor})}/><button onClick={()=>onHide(`wall:${side}`)}>Hide wall</button></>}
    {openingNotice&&<p role="status">{openingNotice}</p>}
    {notice&&<p className={styles.placementNotice} role="status">{notice}</p>}
  </div>;
}
export function RoomControls({design,onChange,onSelect,onBoundary}:{design:KitchenDesign;onChange:(d:KitchenDesign)=>void;onSelect:(id:string)=>void;onBoundary:(side:WallSide,delta:number)=>void}){
  const walls=design.roomWalls??defaultWalls();
  const [notice,setNotice]=useState('');
  return <div className={styles.directBody}><p>{design.gridColumns?'Resize pieces within the room. Add windows and doors below.':'Move each room boundary independently. Windows remain in their openings.'}</p>{WALL_SIDES.map(side=><div className={styles.wallRow} key={side}><label><input type="checkbox" checked={walls[side].enabled} onChange={e=>onChange({...design,roomWalls:{...walls,[side]:{...walls[side],enabled:e.target.checked}}})}/>{side}</label>{!design.gridColumns&&<><button aria-label={`Move ${side} wall inward 12 inches`} onClick={()=>onBoundary(side,-12)}>−12″</button><button aria-label={`Move ${side} wall outward 12 inches`} onClick={()=>onBoundary(side,12)}>+12″</button></>}<button onClick={()=>onSelect(`wall:${side}`)}>Edit</button></div>)}<p className={styles.directHint}>Room: {(design.roomWidth/12).toFixed(1)} × {(design.roomDepth/12).toFixed(1)} ft</p><div className={styles.directActions}>{(['window','door'] as const).map(kind=><button key={kind} disabled={fitOpenings(design).length>=24} onClick={()=>{const id=`${kind}-${crypto.randomUUID()}`,next=addOpening(design,kind,id);if(next){onChange(next);onSelect(id);setNotice('');}else setNotice('No clear opening on the enabled walls. Enable another wall or move an existing opening.');}}>Add {kind}</button>)}</div>{notice&&<p role="status">{notice}</p>}{fitOpenings(design).map((o,i)=><button className={styles.openingRow} key={o.id} onClick={()=>onSelect(o.id)}>{o.wall} {o.kind} {i+1} <span>{o.width}″ × {o.height}″</span></button>)}</div>;
}
