'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUp, ArrowDown, ArrowClockwise, EyeSlash, Trash } from '@phosphor-icons/react';
import { findPlacement } from './placement';
import { KIND_NAMES, SIZE_LIMITS, type ComponentKind, type KitchenDesign, type KitchenComponent } from './kitchen';
import { defaultWalls, fitOpenings, editOpening as resolveOpening, addOpening, WALL_SIDES, wallLength, type WallSide, type RoomOpening } from './room';
import { ColorPicker } from './FinishControls';
import MaterialPicker from './MaterialPicker';
import styles from './studio.module.css';
export function NumberEdit({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(n:number)=>void}){
  return <label className={styles.directNumber}>{label}<span><input key={value} type="number" aria-label={label} defaultValue={value} min={min} max={max} step={.5} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}} onBlur={e=>{if(Number.isFinite(e.target.valueAsNumber)){const n=Math.max(min,Math.min(max,Math.round(e.target.valueAsNumber*2)/2));if(n!==value)onChange(n);}e.target.value=String(value);}}/>″</span></label>;
}
interface Props { design:KitchenDesign; selected:string|null; onSelect:(id:string|null)=>void; onChange:(d:KitchenDesign)=>void; onEdit:(p:Partial<KitchenComponent>)=>unknown; onReplace:(kind:ComponentKind)=>void; onAdd:(kind:ComponentKind)=>void; onShift:(x:number,y:number)=>void; onHide:(id:string)=>void; onBoundary:(side:WallSide,delta:number)=>void; flow:boolean; onFlow:(v:boolean)=>void; notice:string; }
export default function DirectEditor({design,selected,onSelect,onChange,onEdit,onReplace,onAdd,onShift,onHide,onBoundary,flow,onFlow,notice}:Props){
  const [addKind,setAddKind]=useState<ComponentKind>('base');
  const [step,setStep]=useState(1),[openingNotice,setOpeningNotice]=useState('');
  const c=design.components.find(c=>c.id===selected),o=fitOpenings(design).find(o=>o.id===selected);
  const side=selected?.startsWith('wall:')?selected.slice(5) as WallSide:null;
  const walls=design.roomWalls??defaultWalls();
  const editOpening=(patch:Partial<RoomOpening>)=>{if(!o)return;const next=resolveOpening(design,{...o,...patch});if(next){onChange(next);setOpeningNotice('');}else setOpeningNotice('Leave space between window and door frames.');};
  return <div className={styles.directBody}>
    <div className={styles.pieceHeading}><h3>{c?.name??(o?`${o.kind==='window'?'Window':'Door'}`:side?`${side[0].toUpperCase()+side.slice(1)} wall`:'Arrange your kitchen')}</h3><p>{selected?'Changes appear in the kitchen as you make them.':'Click a piece in the kitchen, or add something new.'}</p></div>
    <div className={styles.pieceChoices}><details className={styles.simpleDetails} open={!selected}><summary>Add a piece</summary><div className={styles.addComponentRow}><label className={styles.selectLabel}>Add component<select aria-label="New component type" value={addKind} onChange={e=>setAddKind(e.target.value as ComponentKind)}>{Object.entries(KIND_NAMES).map(([kind,name])=><option key={kind} value={kind}>{name}</option>)}</select></label><button disabled={design.components.length>=200} onClick={()=>onAdd(addKind)}>Add</button></div></details>
    <details className={styles.simpleDetails} open={!selected}><summary>{selected?'Choose another piece':'Choose from a list'}</summary><label className={styles.selectLabel}>Select an element to edit<select value={selected??''} onChange={e=>onSelect(e.target.value||null)}><option value="">Select in the scene</option>{design.components.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}{WALL_SIDES.map(s=><option key={s} value={`wall:${s}`}>{s} wall</option>)}{fitOpenings(design).map((o,i)=><option key={o.id} value={o.id}>{o.wall} {o.kind} {i+1}</option>)}</select></label></details></div>

    {c&&<><label className={styles.selectLabel}>Replace with<select aria-label="Component type" value={c.kind} onChange={e=>onReplace(e.target.value as ComponentKind)}>{Object.entries(KIND_NAMES).map(([kind,name])=><option key={kind} value={kind}>{name}</option>)}</select></label></>}
    {(c||o)&&<><div className={styles.shiftControls}><span>{c?'Swap places':'Move'}</span>{[{name:'left',x:-1,y:0,Icon:ArrowLeft},{name:'right',x:1,y:0,Icon:ArrowRight},{name:'up',x:0,y:1,Icon:ArrowUp},{name:'down',x:0,y:-1,Icon:ArrowDown}].map(({name,x,y,Icon})=><button key={name} aria-label={`Shift ${name}`} title={`Shift ${name}`} onClick={()=>c?onShift(x,y):editOpening(x?{offset:o!.offset+x*step}:{bottom:o!.bottom+y*step})}><Icon size={18}/></button>)}<select hidden={!!c} aria-label="Shift distance" value={step} onChange={e=>setStep(Number(e.target.value))}>{[1,3,6,12].map(n=><option key={n} value={n}>{n}″</option>)}</select></div><p className={styles.directHint}>{c?'Swap places with a neighbouring piece. The counter stays connected.':'Left/right along the wall; up/down changes sill height.'}</p></>}
    {c&&<>
      <div className={styles.primaryWidth}><NumberEdit label="Width" value={c.width} min={SIZE_LIMITS[c.kind].width[0]} max={SIZE_LIMITS[c.kind].width[1]} onChange={width=>onEdit({width})}/></div>
      <div className={styles.directActions}><button onClick={()=>onEdit({rotation:(c.rotation+90)%360})}><ArrowClockwise size={16}/>Rotate 90°</button><button className={styles.removeComponent} onClick={()=>{onChange({...design,components:design.components.filter(p=>p.id!==c.id)});onSelect(null);}}><Trash size={14}/> Remove selected component</button></div>
      {c.kind==='sink'&&<p className={styles.directHint}>Width resizes the bowl, cutout, and sink cabinet together.</p>}
      <button disabled={design.components.length>=200} onClick={()=>{const copy=findPlacement({...c,id:`${c.kind}-${crypto.randomUUID()}`,x:c.x+c.width},design.components,design.roomWidth,design.roomDepth);if(copy){onChange({...design,components:[...design.components,copy]});onSelect(copy.id);}}}>Duplicate</button>
      <details className={styles.simpleDetails}><summary>Size & placement</summary>      <label className={styles.flowToggle}><input type="checkbox" checked={flow} onChange={e=>onFlow(e.target.checked)}/>Adjust connected pieces & room</label>
<div className={styles.directNumbers}>{(['depth','height'] as const).map(k=><NumberEdit key={k} label={k} value={c[k]} min={SIZE_LIMITS[c.kind][k][0]} max={SIZE_LIMITS[c.kind][k][1]} onChange={v=>onEdit({[k]:v})}/>)}</div><button onClick={()=>onHide(c.id)}><EyeSlash size={16}/>Hide this piece</button><div className={styles.directNumbers}><NumberEdit label="Position X" value={c.x} min={-360} max={360} onChange={x=>onEdit({x})}/><NumberEdit label="Position Z" value={c.z} min={-360} max={360} onChange={z=>onEdit({z})}/></div></details><details className={styles.simpleDetails}><summary>Colour & countertop</summary><ColorPicker label="Component colour" value={c.color??(c.kind==='upper'?design.upperColor:c.kind==='island'?design.islandColor:design.cabinetColor)} onChange={color=>onEdit({color})}/>{!['upper','pantry','range','fridge'].includes(c.kind)&&<MaterialPicker label="Component countertop" value={c.material??design.countertop} onChange={material=>onEdit({material})}/>}<button onClick={()=>onEdit({color:undefined,material:undefined})}>Use kitchen finishes</button></details>

    </>}
    {o&&<><label className={styles.selectLabel}>Wall<select value={o.wall} onChange={e=>editOpening({wall:e.target.value as WallSide})}>{WALL_SIDES.map(s=><option key={s}>{s}</option>)}</select></label><div className={styles.directNumbers}><NumberEdit label="Opening width" value={o.width} min={12} max={144} onChange={width=>editOpening({width})}/><NumberEdit label="Opening height" value={o.height} min={12} max={140} onChange={height=>editOpening({height})}/><NumberEdit label="Sill height" value={o.bottom} min={0} max={144} onChange={bottom=>editOpening({bottom})}/><NumberEdit label="Along wall" value={o.offset} min={-wallLength(design,o.wall)/2} max={wallLength(design,o.wall)/2} onChange={offset=>editOpening({offset})}/></div><div className={styles.directActions}><button onClick={()=>onHide(o.id)}>Hide</button><button onClick={()=>{onChange({...design,openings:fitOpenings(design).filter(p=>p.id!==o.id)});onSelect(null);}}>Remove</button></div></>}
    {side&&<><label className={styles.flowToggle}><input type="checkbox" checked={walls[side].enabled} onChange={e=>onChange({...design,roomWalls:{...walls,[side]:{...walls[side],enabled:e.target.checked}}})}/>Include {side} wall</label><NumberEdit label="Wall height" value={walls[side].height} min={96} max={144} onChange={height=>{const d={...design,roomWalls:{...walls,[side]:{...walls[side],height}}};onChange({...d,openings:fitOpenings(d)});}}/><div className={styles.directActions}><button onClick={()=>onBoundary(side,-12)}>Move inward 12″</button><button onClick={()=>onBoundary(side,12)}>Move outward 12″</button></div><p className={styles.directHint}>Windows stay attached to their wall.</p><ColorPicker label="Wall colour" value={design.wallColor} onChange={wallColor=>onChange({...design,wallColor})}/><button onClick={()=>onHide(`wall:${side}`)}>Hide wall</button></>}
    {openingNotice&&<p role="status">{openingNotice}</p>}
    {notice&&<p className={styles.placementNotice} role="status">{notice}</p>}
  </div>;
}
export function RoomControls({design,onChange,onSelect,onBoundary}:{design:KitchenDesign;onChange:(d:KitchenDesign)=>void;onSelect:(id:string)=>void;onBoundary:(side:WallSide,delta:number)=>void}){
  const walls=design.roomWalls??defaultWalls();
  const [notice,setNotice]=useState('');
  return <div className={styles.directBody}><p>Move each room boundary independently. Attached pieces follow it; windows remain in their openings.</p>{WALL_SIDES.map(side=><div className={styles.wallRow} key={side}><label><input type="checkbox" checked={walls[side].enabled} onChange={e=>onChange({...design,roomWalls:{...walls,[side]:{...walls[side],enabled:e.target.checked}}})}/>{side}</label><button aria-label={`Move ${side} wall inward 12 inches`} onClick={()=>onBoundary(side,-12)}>−12″</button><button aria-label={`Move ${side} wall outward 12 inches`} onClick={()=>onBoundary(side,12)}>+12″</button><button onClick={()=>onSelect(`wall:${side}`)}>Edit</button></div>)}<p className={styles.directHint}>Room: {(design.roomWidth/12).toFixed(1)} × {(design.roomDepth/12).toFixed(1)} ft</p><div className={styles.directActions}>{(['window','door'] as const).map(kind=><button key={kind} disabled={fitOpenings(design).length>=24} onClick={()=>{const id=`${kind}-${crypto.randomUUID()}`,next=addOpening(design,kind,id);if(next){onChange(next);onSelect(id);setNotice('');}else setNotice('No clear opening on the enabled walls. Enable another wall or move an existing opening.');}}>Add {kind}</button>)}</div>{notice&&<p role="status">{notice}</p>}{fitOpenings(design).map((o,i)=><button className={styles.openingRow} key={o.id} onClick={()=>onSelect(o.id)}>{o.wall} {o.kind} {i+1} <span>{o.width}″ × {o.height}″</span></button>)}</div>;
}
