'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { createRoom, applyCommand, publicView, tickRoom, recoverHost, validateDeck, effectiveCard } = require('../src/one-night/engine');
let clock = 100000;
function game(roles, centers = ['werewolf', 'villager', 'tanner']) {
    const room = createRoom({ code: 'MOON', hostId: 'a0', hostName: 'Host', now: clock });
    for (let i = 1; i < roles.length; i++) applyCommand(room, `a${i}`, { type: 'requestJoin', name: `Player ${i + 1}` }, clock);
    room.seats.forEach((seat, i) => { seat.number = i + 1; seat.originalRoleId = roles[i]; seat.nightRoleId = roles[i]; room.cards[seat.id] = { id: `card${i}`, roleId: roles[i] }; room.marks[seat.id] = 'clarity'; });
    centers.forEach((roleId, i) => { room.cards[`center:${i}`] = { id: `center${i}`, roleId }; });
    room.status = 'playing'; room.roleDeck = [...roles, ...centers]; room.schedule = []; room.nightIndex = 0; return room;
}
function at(room, role, actorIndexes) { room.phase = { id: `phase-${++clock}`, kind: 'night', step: role, roleId: role, nightStage: 'acting', cueIds: [], deadline: null }; room.nightActors = actorIndexes.map(i => room.seats[i].id); room.schedule = [{ roleId: role, step: role, order: 1 }]; room.nightIndex = 0; }
function act(room, i, targets = [], extra = {}) { const action = publicView(room, `a${i}`, clock).me.action; assert.ok(action, `action exists for ${room.phase.step} seat ${i}`); applyCommand(room, `a${i}`, { type: 'act', expectedPhaseId: room.phase.id, actionId: action.id, targets: targets.map(t => typeof t === 'number' ? room.seats[t].id : t), ...extra }, ++clock); }
function vote(room, choices) { room.phase = { id: `vote-${++clock}`, kind: 'voting', step: 'voting', cueIds: [] }; choices.forEach((target, i) => applyCommand(room, `a${i}`, { type: 'vote', targetId: room.seats[target].id, expectedPhaseId: room.phase.id }, ++clock)); applyCommand(room, 'a0', { type: 'finishVote', expectedPhaseId: room.phase.id }, ++clock); return room.result; }
const sid = (room, i) => room.seats[i].id;
test('deal waits for every player and prevents mid-game seat changes', () => { const room = createRoom({ code: 'TEST', hostId: 'a0', hostName: 'A', now: clock }); ['B', 'C'].forEach((name, i) => applyCommand(room, `a${i + 1}`, { type: 'requestJoin', name }, clock)); applyCommand(room, 'a0', { type: 'start' }, clock); assert.equal(room.phase.kind, 'ready'); assert.throws(() => applyCommand(room, 'a0', { type: 'startNight' }, clock), /Every player/); room.seats.forEach((s, i) => applyCommand(room, `a${i}`, { type: 'ready' }, clock)); applyCommand(room, 'a0', { type: 'startNight' }, clock); assert.equal(room.phase.nightStage, 'opening'); assert.throws(() => applyCommand(room, 'a0', { type: 'reorderSeats', seatIds: room.seats.map(s => s.id).reverse() }, clock), /not available/); });
test('exact N+3 valid catalogue cards and paired Masons', () => { assert.throws(() => validateDeck(['werewolf', 'seer', 'robber'], 3), /three more/); assert.throws(() => validateDeck(['werewolf', 'werewolf', 'mason', 'seer', 'robber', 'villager'], 3), /both Mason/); });
test('Robber gets immutable inspection; later swap does not change original action or private card', () => { const r = game(['robber', 'werewolf', 'troublemaker']); at(r, 'robber', [0]); act(r, 0, [1]); const old = publicView(r, 'a0', clock); assert.match(old.me.knowledge[0].text.en, /Werewolf/); assert.equal(old.me.roleId, 'robber'); at(r, 'troublemaker', [2]); act(r, 2, [0, 1]); assert.equal(effectiveCard(r, sid(r, 0)).roleId, 'robber'); assert.equal(publicView(r, 'a0', clock).me.knowledge[0].text.en, old.me.knowledge[0].text.en); assert.equal(publicView(r, 'a1', clock).me.roleId, 'werewolf'); });
test('Seer mode separates one-player and two-center inspections', () => { const r = game(['seer', 'villager', 'werewolf']); at(r, 'seer', [0]); act(r, 0, [], { choice: 'center' }); const d = publicView(r, 'a0', clock).me.action; assert.equal(d.min, 2); assert.ok(d.targets.every(t => t.id.startsWith('center:'))); act(r, 0, ['center:0', 'center:1']); assert.equal(r.seats[0].knowledge.length, 2); });
test('Witch inspection commits to mandatory exchange with a new action id', () => { const r = game(['witch', 'villager', 'werewolf']); at(r, 'witch', [0]); const old = publicView(r, 'a0', clock).me.action.id; act(r, 0, ['center:0']); const d = publicView(r, 'a0', clock).me.action; assert.notEqual(d.id, old); assert.equal(d.canSkip, false); assert.throws(() => act(r, 0, [], { skip: true }), /must be completed/); act(r, 0, [1]); assert.equal(r.cards[sid(r, 1)].roleId, 'werewolf'); });
test('PI must stop immediately after actual wolf, but not copying card', () => { const r = game(['paranormalInvestigator', 'werewolf', 'villager']); at(r, 'paranormalInvestigator', [0]); act(r, 0, [1]); assert.equal(r.phase.nightStage, 'closing'); assert.equal(effectiveCard(r, sid(r, 0)).team, 'wolf'); const q = game(['paranormalInvestigator', 'doppelganger', 'villager']); q.cards[sid(q, 1)].copiedRoleId = 'werewolf'; at(q, 'paranormalInvestigator', [0]); act(q, 0, [1]); assert.ok(publicView(q, 'a0', clock).me.action); assert.equal(effectiveCard(q, sid(q, 0)).team, 'village'); });
test('Sentinel blocks Drunk/Robber/Insomniac and card swaps but not mark swaps', () => { const r = game(['drunk', 'robber', 'insomniac', 'gremlin']); r.shields = r.seats.slice(0, 3).map(s => s.id); at(r, 'drunk', [0]); act(r, 0); assert.equal(r.cards[sid(r, 0)].roleId, 'drunk'); at(r, 'insomniac', [2]); act(r, 2); assert.equal(r.seats[2].knowledge.length, 0); at(r, 'robber', [1]); assert.equal(publicView(r, 'a1', clock).me.action.targets.length, 0); act(r, 1, [], { skip: true }); r.marks[sid(r, 0)] = 'vampire'; at(r, 'gremlin', [3]); act(r, 3, [0, 1], { choice: 'marks' }); assert.equal(r.marks[sid(r, 1)], 'vampire'); });
test('Alpha swaps separate fourth center; Witch can inspect it afterward', () => { const r = game(['alphaWolf', 'witch', 'villager'], ['seer', 'robber', 'drunk', 'werewolf']); at(r, 'alphaWolf', [0]); act(r, 0, [2]); assert.equal(r.cards['center:3'].roleId, 'villager'); assert.equal(r.cards[sid(r, 2)].roleId, 'werewolf'); at(r, 'witch', [1]); assert.ok(publicView(r, 'a1', clock).me.action.targets.some(t => t.id === 'center:3')); });
test('Doppelganger Robber performs immediately and copied metadata follows exchanged card', () => { const r = game(['doppelganger', 'robber', 'werewolf']); at(r, 'doppelganger', [0]); act(r, 0, [1]); assert.equal(publicView(r, 'a0', clock).me.action.roleId, 'robber'); act(r, 0, [2]); assert.equal(r.cards[sid(r, 2)].roleId, 'doppelganger'); assert.equal(effectiveCard(r, sid(r, 2)).roleId, 'robber'); assert.equal(effectiveCard(r, sid(r, 0)).roleId, 'werewolf'); });
test('Doppelganger seeing Copycat inherits role without second action', () => { const r = game(['doppelganger', 'copycat', 'werewolf']); r.cards[sid(r, 1)].copiedRoleId = 'seer'; r.seats[1].nightRoleId = 'seer'; r.seats[1].copyMode = 'copycat'; at(r, 'doppelganger', [0]); act(r, 0, [1]); assert.equal(effectiveCard(r, sid(r, 0)).roleId, 'seer'); assert.equal(r.phase.nightStage, 'closing'); });
test('marks stay with players when cards move, artifact overrides Vampire mark', () => { const r = game(['troublemaker', 'hunter', 'werewolf']); r.marks[sid(r, 1)] = 'vampire'; at(r, 'troublemaker', [0]); act(r, 0, [1, 2]); assert.equal(r.marks[sid(r, 1)], 'vampire'); assert.equal(effectiveCard(r, sid(r, 1)).team, 'vampire'); r.artifacts[sid(r, 1)] = 'brand'; assert.deepEqual(effectiveCard(r, sid(r, 1)), { roleId: 'villager', team: 'village' }); });
test('highest vote tie kills all tied players, one vote each kills nobody', () => { const r = game(['werewolf', 'villager', 'seer', 'robber']); const result = vote(r, [1, 0, 0, 1]); assert.deepEqual(new Set(result.deaths), new Set([sid(r, 0), sid(r, 1)])); const q = game(['werewolf', 'villager', 'seer']); assert.equal(vote(q, [1, 2, 0]).deaths.length, 0); });
test('bodyguard vote protects and falls through to next qualifying rank', () => { const r = game(['bodyguard', 'werewolf', 'villager', 'seer', 'robber', 'tanner']); const result = vote(r, [1, 2, 1, 1, 2, 1]); assert.deepEqual(result.deaths, [sid(r, 2)]); assert.equal(result.counts[sid(r, 1)], 3); });
test('hunter chains death; Tanner dying blocks wolf win', () => { const r = game(['hunter', 'werewolf', 'villager']); const result = vote(r, [1, 0, 0]); assert.deepEqual(new Set(result.deaths), new Set([sid(r, 0), sid(r, 1)])); const q = game(['tanner', 'werewolf', 'villager']); const x = vote(q, [1, 0, 0]); assert.deepEqual(x.winners, [sid(q, 0)]); });
test('Love death bypasses protection and role-changing artifact removes Hunter power', () => { const r = game(['hunter', 'bodyguard', 'villager', 'werewolf']); r.marks[sid(r, 0)] = r.marks[sid(r, 2)] = 'love'; r.artifacts[sid(r, 0)] = 'brand'; const result = vote(r, [3, 2, 0, 0]); assert.ok(result.deaths.includes(sid(r, 2))); assert.ok(!result.deaths.includes(sid(r, 3))); });
test('vampire-marked wolf is not an active wolf faction in Epic Battle', () => { const r = game(['werewolf', 'vampire', 'villager']); r.marks[sid(r, 0)] = 'vampire'; const result = vote(r, [1, 2, 1]); assert.equal(result.epic, false); assert.deepEqual(result.deaths, [sid(r, 1)]); });
test('Epic Battle kills top two vote groups, with tie-first exception', () => { const r = game(['werewolf', 'vampire', 'villager', 'seer']); const result = vote(r, [1, 0, 0, 2]); assert.equal(result.epic, true); assert.equal(result.deaths.length, 3); const q = game(['werewolf', 'vampire', 'villager', 'seer']); assert.equal(vote(q, [1, 0, 0, 1]).deaths.length, 2); });
test('Assassin and apprentice can co-win with village', () => { const r = game(['assassin', 'apprenticeAssassin', 'werewolf', 'villager']); r.marks[sid(r, 2)] = 'assassin'; const result = vote(r, [2, 0, 0, 2]); assert.ok(result.winners.includes(sid(r, 0))); assert.ok(result.winners.includes(sid(r, 1))); assert.ok(result.winners.includes(sid(r, 3))); });
test('Disease excludes voters even when team wins, Traitor requires teammate death', () => { const r = game(['werewolf', 'diseased', 'villager', 'seer']); r.marks[sid(r, 0)] = 'disease'; const result = vote(r, [1, 0, 0, 0]); assert.equal(result.winners.length, 0); const q = game(['werewolf', 'villager', 'seer', 'robber']); q.marks[sid(q, 1)] = 'traitor'; const x = vote(q, [2, 0, 0, 2]); assert.ok(x.winners.includes(sid(q, 1))); });
test('disconnected actors never auto-skip; hidden state is not exposed to host', () => { const r = game(['seer', 'werewolf', 'villager']); at(r, 'seer', [0]); assert.equal(tickRoom(r, clock + 1e9), false); const v = publicView(r, 'a1', clock); assert.equal(v.me.action, null); assert.equal(v.cards, undefined); assert.ok(!v.seats.some(s => s.roleId)); assert.equal(v.nightActors, undefined); });
test('rejoin replacement preserves action/card and revokes prior session; disband clears everyone', () => { const r = game(['seer', 'werewolf', 'villager']); at(r, 'seer', [0]); applyCommand(r, 'a1', { type: 'leave' }, clock); const card = structuredClone(r.cards[sid(r, 1)]); applyCommand(r, 'new', { type: 'requestJoin', name: 'Returning B' }, clock); applyCommand(r, 'a0', { type: 'approveJoin', requestId: r.requests[0].id, replaceSeatId: sid(r, 1) }, clock); assert.deepEqual(r.cards[sid(r, 1)], card); assert.equal(publicView(r, 'a1', clock).me, null); assert.equal(publicView(r, 'new', clock).me.roleId, 'werewolf'); applyCommand(r, 'a0', { type: 'disbandRoom' }, clock); assert.equal(r.status, 'disbanded'); assert.equal(publicView(r, 'new', clock).me, null); });
test('invalid actions rollback all state, recovery moves host control', () => { const r = game(['robber', 'werewolf', 'villager']); at(r, 'robber', [0]); const before = JSON.stringify(r); assert.throws(() => act(r, 0, [0]), /valid targets/); assert.equal(JSON.stringify(r), before); recoverHost(r, 'recovered', clock); assert.equal(publicView(r, 'a0', clock).me, null); assert.ok(publicView(r, 'recovered', clock).isHost); });
test('Insomniac viewing a received Doppelganger card does not learn its secret copied role', () => { const r = game(['insomniac', 'doppelganger', 'werewolf']); r.cards[sid(r, 0)] = { id: 'copied', roleId: 'doppelganger', copiedRoleId: 'tanner' }; at(r, 'insomniac', [0]); act(r, 0); assert.equal(r.seats[0].knowledge.length, 1); assert.ok(!r.seats[0].knowledge[0].text.en.includes('Tanner')); });
test('Doppelganger copying Copycat learns no chosen identity and receives no later copied action', () => { const r = game(['doppelganger', 'copycat', 'werewolf']); r.cards[sid(r, 1)].copiedRoleId = 'seer'; r.seats[1].nightRoleId = 'seer'; r.seats[1].copyMode = 'copycat'; at(r, 'doppelganger', [0]); act(r, 0, [1]); assert.ok(r.seats[0].knowledge.every(k => !k.text.en.includes('Seer'))); r.schedule = [{ roleId: 'seer', step: 'seer', order: 5 }]; r.nightIndex = 0; r.phase = { id: 'seer-opening', kind: 'night', step: 'seer', roleId: 'seer', nightStage: 'opening', deadline: clock, cueIds: [] }; tickRoom(r, clock); assert.equal(publicView(r, 'a0', clock).me.action, null); assert.ok(publicView(r, 'a1', clock).me.action); });
test('every narration stage gets a fresh phase id and absent-action deadline remains private', () => { const r = game(['villager', 'werewolf', 'tanner']); r.schedule = [{ roleId: 'seer', step: 'seer', order: 5 }]; r.phase = { id: 'open', kind: 'night', step: 'seer', roleId: 'seer', nightStage: 'opening', deadline: clock, cueIds: [] }; tickRoom(r, clock); const actingId = r.phase.id; assert.notEqual(actingId, 'open'); assert.ok(r.phase.deadline > clock); assert.equal(publicView(r, 'a0', clock).phase.deadline, null); tickRoom(r, r.phase.deadline); assert.notEqual(r.phase.id, actingId); assert.equal(r.phase.nightStage, 'closing'); });
test('every core role action completes through its published descriptor, without host skipping active actors', () => {
    const roles = require('../src/one-night/core-roles.json');
    for (const role of roles.filter(r => r.order != null)) {
        const r = game([role.id, 'werewolf', 'villager', 'hunter', 'tanner']);
        const step = role.id === 'master' ? 'vampire' : role.id;
        r.schedule = [{ roleId: step, step, order: role.order }];
        r.phase = { id: `open-${role.id}`, kind: 'night', step, roleId: step, nightStage: 'opening', deadline: clock, cueIds: [] };
        if (role.id === 'alphaWolf') r.cards['center:3'] = { id: 'extra', roleId: 'werewolf' };
        tickRoom(r, clock);
        let turns = 0;
        while (r.phase.nightStage === 'acting' && r.nightActors.length && turns++ < 12) {
            for (const actor of r.nightActors) {
                const index = r.seats.findIndex(s => s.id === actor);
                const d = publicView(r, `a${index}`, clock).me.action;
                if (!d) continue;
                const choice = d.options?.[0]?.id;
                const selected = d.targets.slice(0, d.min).map(t => t.id);
                act(r, index, selected, { choice });
                if (r.phase.nightStage !== 'acting') break;
            }
        }
        assert.ok(r.phase.nightStage === 'closing' || !r.nightActors.length, `${role.id} must complete`);
    }
});
test('public center card view exposes only cards explicitly revealed by a power', () => { const r = game(['seer', 'werewolf', 'villager']); r.revealed = ['center:1']; const view = publicView(r, 'a0', clock); assert.deepEqual(view.centerCards.map(c => c.roleId), [undefined, 'villager', undefined]); });
test('Doppelganger Alpha may target an unknown wolf but never the Alpha it copied', () => { const r = game(['doppelganger', 'alphaWolf', 'werewolf', 'villager'], ['seer', 'robber', 'drunk', 'werewolf']); at(r, 'doppelganger', [0]); act(r, 0, [1]); const targets = publicView(r, 'a0', clock).me.action.targets.map(t => t.id); assert.ok(targets.includes(sid(r, 2))); assert.ok(!targets.includes(sid(r, 1))); act(r, 0, [2]); });
test('Fear hides wolves from awake wolves but Minion still identifies them', () => { const r = game(['werewolf', 'mysticWolf', 'minion', 'villager']); r.seats[1].duskMark = 'fear'; r.schedule = [{ roleId: 'werewolf', step: 'werewolf', order: 2 }]; r.phase = { id: 'wolves-open', kind: 'night', step: 'werewolf', roleId: 'werewolf', nightStage: 'opening', deadline: clock, cueIds: [] }; tickRoom(r, clock); assert.deepEqual(r.nightActors, [sid(r, 0)]); assert.ok(!r.seats[0].knowledge.some(k => k.text.en.includes('#2'))); r.schedule = [{ roleId: 'minion', step: 'minion', order: 3 }]; r.phase = { id: 'minion-open', kind: 'night', step: 'minion', roleId: 'minion', nightStage: 'opening', deadline: clock, cueIds: [] }; tickRoom(r, clock); assert.ok(r.seats[2].knowledge.some(k => k.text.en.includes('#2'))); });
test('Dream Wolf is recognized without receiving a night action or creating a lone wolf', () => { const r = game(['werewolf', 'dreamWolf', 'villager']); r.schedule = [{ roleId: 'werewolf', step: 'werewolf', order: 2 }]; r.phase = { id: 'dream-open', kind: 'night', step: 'werewolf', roleId: 'werewolf', nightStage: 'opening', deadline: clock, cueIds: [] }; tickRoom(r, clock); assert.equal(publicView(r, 'a1', clock).me.action, null); assert.ok(r.seats[0].knowledge.some(k => k.text.en.includes('#2'))); assert.equal(publicView(r, 'a0', clock).me.action.targets.length, 0); });
test('a full sixteen-seat lobby still admits players into reserved matching seats', () => { const r = createRoom({ code: 'FULL', hostId: 'a0', hostName: 'Host', now: clock }); for (let i = 1; i < 16; i++) applyCommand(r, 'a0', { type: 'addSeat', name: `Reserved ${i}` }, clock); const reservedId = r.seats[15].id; applyCommand(r, 'joined', { type: 'requestJoin', name: 'Reserved 15' }, clock); assert.equal(r.seats.length, 16); assert.equal(publicView(r, 'joined', clock).me.seatId, reservedId); assert.throws(() => applyCommand(r, 'overflow', { type: 'requestJoin', name: 'Unexpected' }, clock), /full/); });
