"use client";
import type { GameView, Language } from '@/lib/oneNightClient';
import styles from './one-night.module.css';

export function NightRecap({view,lang,roleName,tokenName}:{view:GameView;lang:Language;roleName:(id:string)=>string;tokenName:(id:string)=>string}) {
  const t=(en:string,zh:string)=>lang==='en'?en:zh;
  const label=(id:string)=>id.startsWith('center:')?t(`Center ${Number(id.split(':')[1])+1}`,`中央牌${Number(id.split(':')[1])+1}`):id.startsWith('reserve:')?t('Reserve card','备用牌'):(()=>{const seat=view.seats.find(s=>s.id===id);return seat?`${seat.number}${lang==='zh'?'号':' ·'} ${seat.name}`:t('Unknown seat','未知座位');})();
  const entries=view.result?.recap?.length?view.result.recap:(view.result?.timeline||[]).map(entry=>({seatId:entry.seatId,roleId:entry.roleId,operations:[entry],changes:[],clues:[]}));
  return <section className={styles.nightRecap} aria-label={t('Night sequence','夜间事件顺序')}><h2>{t('What happened overnight','夜间事件回顾')}</h2><p>{t('In the order actions happened. These details are revealed only after the vote.','按实际行动顺序排列，所有秘密信息仅在投票结束后公开。')}</p>{entries.length?<ol>{entries.map((entry,index)=><li key={index}><h3>{label(entry.seatId)} · {roleName(entry.roleId)}</h3>{'skipped' in entry&&entry.skipped&&<p>{'hostSkipped' in entry&&entry.hostSkipped?t('Host skipped this action.','房主跳过此行动。'):t('Chose not to act.','选择不发动技能。')}</p>}{entry.operations.map((op,i)=><p key={i}>{op.type==='move'?(op.direction?t(`Rotated cards ${op.direction==='clockwise'?'clockwise':'counterclockwise'}: `,`${op.direction==='clockwise'?'顺时针':'逆时针'}传递身份牌：`):t('Swapped cards: ','交换身份牌：')):op.type==='view'?t('Checked: ','查看：'):t('Action: ','行动：')}{op.targets.map(label).join(op.type==='move'&&!op.direction?' ↔ ':' → ')}</p>)}{entry.changes.map(change=><p key={change.id} className={styles.recapChange}><strong>{label(change.id)}</strong>{change.before?.roleId!==change.after.roleId&&<> · {roleName(change.before?.roleId||'')} → {roleName(change.after.roleId)}</>}{change.before?.mark!==change.after.mark&&<> · {t('Mark','标记')}: {tokenName(change.before?.mark||'clarity')} → {tokenName(change.after.mark||'clarity')}</>}{change.before?.artifact!==change.after.artifact&&<> · {t('Artifact','神器')}: {change.after.artifact?tokenName(change.after.artifact):t('None','无')}</>}{change.before?.shielded!==change.after.shielded&&<> · {change.after.shielded?t('Shield added','获得护盾'):t('Shield removed','移除护盾')}</>}</p>)}{!!entry.clues.length&&<details><summary>{t('Information learned','获得的线索')}</summary>{entry.clues.map((clue,i)=><p key={i}>{clue[lang]}</p>)}</details>}{!entry.operations.length&&!entry.changes.length&&!entry.clues.length&&!('skipped' in entry&&entry.skipped)&&<p>{t('Completed their turn without moving cards.','完成回合，未移动身份牌。')}</p>}</li>)}</ol>:<p>{t('No recorded night actions.','没有已记录的夜间行动。')}</p>}</section>;
}
